# Generated by Django 2.0.5 on 2018-05-18 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_subscriptions", "0008_auto_20180518_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="code",
            field=models.CharField(
                default="abo",
                help_text="Codes must be unique per user. Allows identifying the subscription.",
                max_length=20,
                verbose_name="code",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="subscription", unique_together={("user", "code")}
        ),
    ]
